#!/bin/sh /etc/rc.common
#
# Copyright (C) 2017 openwrt-system-monitor
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
START=99
STOP=15
NAME=sysmonitor
APP_PATH=/usr/share/$NAME

stop()
{
	set sysmonitor.sysmonitor.enable=0
	set commit sysmonitor
}
start()
{
	[ -f /etc/config/upnpd ] && {
	iptables -N MINIUPNPD
	iptables -t nat -N MINIUPNPD
	[ $(iptables -L MINIUPNPD -nv|grep MINIUPNPD|cut -d'(' -f2|cut -d' ' -f1) == 0 ] && iptables -I FORWARD -i pppoe-wan -o br-lan -j MINIUPNPD
	[ $(iptables -t nat -L MINIUPNPD -nv|grep MINIUPNPD|cut -d'(' -f2|cut -d' ' -f1) == 0 ] && iptables -t nat -I PREROUTING -i pppoe-wan -j MINIUPNPD
	}
	/usr/share/sysmonitor/sysapp.sh vlan
	if [ $(uci get dhcp.lan.dhcpv6) == 'server' ];  then
		uci set dhcp.lan.force='1'
		uci set dhcp.lan.ra='relay'
		uci set dhcp.lan.dhcpv6='relay'
		uci set dhcp.lan.ndp='relay'
		uci set dhcp.lan.ra_management=''
		uci commit dhcp
		/etc/init.d/dnsmasq reload >/dev/null
	fi
	if [ $(uci get sysmonitor.sysmonitor.bbr) == 1 ];  then
		sysctl -w net.ipv4.tcp_congestion_control=bbr
	else
		sysctl -w net.ipv4.tcp_congestion_control=cubic
	fi
	[ -f /etc/init.d/ipsec ] && {
	if [ $(uci get sysmonitor.sysmonitor.ipsec) == 1 ];  then
		uci set ipsec.ipsec.enabled='1'
		uci commit ipsec
		[ $(ps -w |grep ipsec/starter|grep -v grep|wc -l) -eq 0 ] && /etc/init.d/ipsec start
	else
		uci set ipsec.ipsec.enabled='0'
		uci commit ipsec
		[ $(ps -w |grep ipsec/starter|grep -v grep|wc -l) -ne 0 ] && /etc/init.d/ipsec stop
	fi
	}
	[ -f /etc/init.d/luci-app-pptp-server ] && {
	if [ $(uci get sysmonitor.sysmonitor.pptp) == 1 ];  then
		uci set luci-app-pptp-server.pptpd.enabled='1'
		uci commit luci-app-pptp-server
		 [ $(ps -w |grep pptpd|grep -v grep|wc -l) -eq 0 ] && /etc/init.d/luci-app-pptp-server start
	else
		uci set luci-app-pptp-server.pptpd.enabled='0'
		uci commit luci-app-pptp-server
		[ $(ps -w |grep pptpd|grep -v grep|wc -l) -ne 0 ] && /etc/init.d/luci-app-pptp-server stop
	fi
	}
	if [ $(uci get sysmonitor.sysmonitor.vpn) == 0 ];  then
		# Stop Passwall
		if [ -f "/etc/init.d/passwall" ]; then
			if [ $(uci get passwall.@global[0].enabled) == 1 ]; then
				uci set passwall.@global[0].enabled=0
				uci commit passwall
				/etc/init.d/passwall stop &
			fi
		fi
		# Stop Shadowsocksr
		if [ -f "/etc/init.d/shadowsocksr" ]; then
			[ "$(ps -w |grep ssr- |grep -v grep |wc -l)" -gt 0 ] && /etc/init.d/shadowsocksr stop &
		fi
	else
		if [ -f "/etc/init.d/passwall" ]; then
			if [ $(uci get passwall.@global[0].tcp_node) != 'nil' ]; then
				uci set passwall.@global[0].enabled=1
				uci commit passwall
				/etc/init.d/passwall restart &
			fi			
		elif [ -f "/etc/init.d/shadowsocksr" ]; then
			/etc/init.d/shadowsocksr restart &
		else
			uci set sysmonitor.sysmonitor.vpn=0
			uci commit sysmonitor
			touch /tmp/sysmonitor
		fi
	fi
	if [ -f "/etc/init.d/smartdns" ]; then
		if [ $(uci get sysmonitor.sysmonitor.smartdnsAD) == 1 ];  then
			sed -i s/'#conf-file \/etc\/smartdns\/anti-ad-for-smartdns.conf'/'conf-file \/etc\/smartdns\/anti-ad-for-smartdns.conf'/ /etc/smartdns/custom.conf
		else
			sed -i s/'#conf-file'/'conf-file'/ /etc/smartdns/custom.conf
			sed -i s/'conf-file \/etc\/smartdns\/anti-ad-for-smartdns.conf'/'#conf-file \/etc\/smartdns\/anti-ad-for-smartdns.conf'/ /etc/smartdns/custom.conf	
		fi
		/etc/init.d/smartdns restart &
	fi
	$APP_PATH/sysapp.sh getip
	$APP_PATH/sysapp.sh getip6
	set sysmonitor.sysmonitor.enable=1
	set commit sysmonitor
	$APP_PATH/sysmonitor.sh &
}


