#!/bin/sh

#uci set luci-app-pptp-server.pptpd.enabled=0
#uci commit luci-app-pptp-server
#uci set ipsec.ipsec.enabled=0
#uci commit ipsec
#uci set zerotier.sample_config.enabled=0
#uci commit zerotier

uci set luci.main.lang='en'
uci commit luci

uci set fstab.@global[0].anon_mount='1'
uci commit fstab

uci set upnpd.config.enabled='1'
uci commit upnpd

uci set system.@system[0].hostname='VAIO'
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

#uci set dhcp.@dnsmasq[0].rebind_protection='0'
uci del_list dhcp.lan.dhcp_option='44,192.168.1.8'
uci add_list dhcp.lan.dhcp_option='44,192.168.1.8'
uci del_list dhcp.lan.list ra_flags='none'
uci add_list dhcp.lan.list ra_flags='none'
uci set dhcp.lan.ra='relay'
uci set dhcp.lan.dhcpv6='relay'
uci set dhcp.lan.ndp='relay'
uci commit dhcp

cat /etc/config/dhcp | grep wan6 > /dev/null
if [ $? -ne 0 ];then
cat >> /etc/config/dhcp <<EOF
config dhcp 'wan6'
	option interface 'wan6'
	option ignore '1'
	option master '1'
	option ra 'relay'
	option dhcpv6 'relay'
	option ndp 'relay'
	list ra_flags 'none'
EOF
fi

uci del_list network.@device[0].ports='lan1'
uci set network.@device[0].stp='1'
#uci set network.@device[0].MTU='1472'
uci set network.globals.ula_prefix=''
uci set network.wan.hostname="VAIOMI"
uci set network.wan.proto='static'
uci set network.wan.ipaddr='192.168.1.119'
uci set network.wan.netmask='255.255.255.0'
uci set network.wan.gateway='192.168.1.110'
uci set network.wan.dns='192.168.1.110'
uci set network.wan.force_link='0'
uci set network.lan.ip6assign=''
uci set network.lan.ipaddr='192.168.88.1'
uci set network.lan.force_link='0'
uci commit network

uci set wireless.radio0.noscan='1'
#uci set wireless.radio0.country="CN"
uci set wireless.radio0.htmode='HT40'
uci set wireless.radio0.channel='8'
uci set wireless.radio0.legacy_rates='0'
uci set wireless.radio0.mu_beamformer='1'
uci set wireless.default_radio0.ssid='VAIOMI'
uci set wireless.default_radio0.key='sonyvaiotz13w'
uci set wireless.default_radio0.encryption='psk-mixed'
#uci set wireless.default_radio0.disabled='1'

#uci set wireless.radio1.country="CN"
uci set wireless.radio1.hwmode='11a'
uci set wireless.radio1.htmode='VHT80'
uci set wireless.radio1.channel='44'
#uci set wireless.radio1.txpower='23'
uci set wireless.radio1.legacy_rates='0'
uci set wireless.radio1.mu_beamformer='1'
uci set wireless.default_radio1.ssid='VAIOMI'
uci set wireless.default_radio1.key='sonyvaiotz13w'
uci set wireless.default_radio1.encryption='psk-mixed'
#uci set wireless.default_radio1.disabled='1'
uci commit wireless

uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='1'
uci set firewall.@zone[1].input='ACCEPT'
uci set firewall.@defaults[0].forward='ACCEPT'
uci commit firewall

sed -i '/192.168.1.8 NAS/d' /etc/hosts
echo '192.168.1.8 NAS' >> /etc/hosts

cat /etc/config/firewall | grep wghome > /dev/null
if [ $? -ne 0 ];then
cat >> /etc/config/firewall <<EOF
config zone
	option name 'wghome'
	option input 'ACCEPT'
	option forward 'ACCEPT'
	option output 'ACCEPT'
	option network 'wghome'

config forwarding
	option dest 'lan'
	option src 'wghome'
EOF
fi

file1='/etc/config/network'
#sed -i "/option ports '1 2 3 6t'/a\\\toption vid '1'" $file1
#sed -i s/"option ports '1 2 3 6t'"/"option ports '1 6t'"/ $file1
#sed -i "/option ports '4 6t'/a\\\toption vid '2'" $file1
#sed -i s/"option ports '4 6t'"/"option ports '2 3 4 6t'"/ $file1

cat /etc/config/network | grep 192.168.9.119 > /dev/null
if [ $? -ne 0 ];then
cat >> /etc/config/network <<EOF
config interface 'wghome'
	option proto 'wireguard'
	option private_key 'OITHHWLDFgCHKaYfRupo+TQhr4kxkJlcGjhNprpO6l4='
	list addresses '192.168.9.119/24'
	list addresses '192.168.8.119/24'
	list addresses '192.168.7.119/24'
	list addresses '192.168.6.119/24'
config wireguard_wghome
	option description 'ALiCloud'
	option persistent_keepalive '25'
	option endpoint_port '51820'
	list allowed_ips '192.168.9.0/24'
	option route_allowed_ips '1'
	option endpoint_host '47.100.183.141'
	option public_key 'GWLcAE1Of7H1iolrSRAK1FYGB5dhwbEMTZvEJxoZYGA='
config wireguard_wghome
	option public_key 'RuCdaOHKPDf2c2kihx2dzBhEDKZnbnhP1N4aUBkzw3A='
	option route_allowed_ips '1'
	list allowed_ips '192.168.8.0/24'
config wireguard_wghome
	option public_key 'HkRSRzDMks74AmFQlnByouVNR6E/o5I+j033QqF1UyI='
	option route_allowed_ips '1'
	list allowed_ips '192.168.7.0/24'
config wireguard_wghome
	option public_key 'ql9g9ngGQMq9cyBaun5QjnyROyh7Cu4zJ9eZwFM6UGw='
	option route_allowed_ips '1'
	list allowed_ips '192.168.6.0/24'
EOF
fi

[ -f /init.d/samba4 ] && {
cat > /etc/config/samba4 <<EOF
config samba
	option workgroup 'WORKGROUP'
	option charset 'UTF-8'
	option description 'Samba on VAIO'

config sambashare
	option name 'music'
	option path '/mnt/music'
	option read_only 'no'
	option guest_ok 'yes'
	option create_mask '0777'
	option dir_mask '0777'
	option force_root '1'

config sambashare
	option name 'app'
	option read_only 'no'
	option guest_ok 'yes'
	option create_mask '0777'
	option dir_mask '0777'
	option path '/mnt/app'
	option force_root '1'
EOF

file='/etc/samba/smb.conf.template'
sed -i  's|#dns proxy = No|dns proxy = Yes|' $file
sed -i  's|#local master = no|local master = Yes|' $file
sed -i  's|#preferred master = yes|preferred master = yes|' $file
sed -i  's|#smb ports = 445 139|smb ports = 445 139|' $file
sed -i  's|#dns proxy = No|dns proxy = Yes|' $file
cat >> $file << EOF
	browseable = yes
	wins support = yes
	wins proxy =  yes
	remote announce
	remote browse sync
	max protocol = SMB2
	min protocol = NT1
EOF
}

[ -f /etc/init.d/minidlna ] && {
sed -i '/media_dir/d' /etc/config/minidlna
uci set minidlna.config.enabled='1'
uci set minidlna.config.friendly_name='VAIO DLNA Server'
uci add_list minidlna.config.media_dir="/mnt/music"
uci commit minidlna
}

[ -f /etc/init.d/ttyd ] && {
cat > /etc/config/ttyd <<EOF
config ttyd
	option command '/bin/login'
	option debug '7'
	option ipv6 '1'
EOF
}

sed -i '/dhcp-option/d' /etc/dnsmasq.conf
echo "#dhcp-option-force=125,00:00:00:00:16:02:06:48:47:57:2d:43:54:03:04:5a:58:48:4e:0b:02:00:55:0a:02:20:00" >> /etc/dnsmasq.conf
echo "#dhcp-option=15" >> /etc/dnsmasq.conf
echo "#dhcp-option=28" >> /etc/dnsmasq.conf

sed -i 's/root:::0:99999:7:::/root:$1$TADtMues$II9qrw8S7H3hYtJASm0tw.:19059:0:99999:7:::/g' /etc/shadow

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
wifi up

/etc/init.d/ipsec disable
/etc/init.d/pptpd disable
/etc/init.d/luci-app-pptp-server disable

exit 0
